### ISSUE TITLE
Hebrew

### ISSUE THREAD

**Issue by mikey641** [emijrp/wikidata#14]
hey. 
can you do this change:

```
#"he": "מחוזות משנה של==> "he": "מחוז משנה ב
#"he": "מחוזות  ==> "he": "מחוז ב
#"he": "נפות ==> "he": "נפה ב
#"he": "מדינות==> "he": "מדינה ב
#"he": "רובעי==> "he": "רובע ב
#"he": "חבלי==> "he": "חבל ב
#"he": "פרובינציות==> "he": "פרובינציה ב
```
Thanks

**Comment by mikey641** [comment]
but first change

מחוזות פדרליים של רוסיה ==> מחוז פדרלי ברוסיה
סובייקטים פדרליים של רוסיה==>סובייקט פדרלי ברוסיה

**Comment by emijrp** [comment]
Where? Please, make a pull request.

**Comment by mikey641** [comment]
sorry. it's in "administrative.descriptions.py", I'm not sure how to open one.
I just need to do a couple replacements using [a find and replace tool](http://textmechanic.com/text-tools/basic-text-tools/find-and-replace-text/) but I can't copy the python code, so can you please do it? thanks

**Comment by mikey641** [comment]
you can close this request. I was able to do it by my self and opened a pull request

**Comment by emijrp** [comment]
Thanks
